apiVersion: apps/v1
kind: Deployment
metadata:
  name: group-a-munity
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: group-a-munity
  template:
    metadata:
      name: group-a-munity
      labels:
        app: group-a-munity
    spec:
      containers:
      - name: group-a-munity
        env:
          - name: POSTGRES_USER
            valueFrom:
              configMapKeyRef:
                name: postgres-config
                key: postgres_user
          - name: POSTGRES_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: postgres-config
                key: postgres_password
          - name: POSTGRES_HOST
            valueFrom:
              configMapKeyRef:
                name: hostname-config
                key: postgres_host
        image: gcr.io/cg-gcp-jee-pt-09-07-22-160/group-a-munity:v1